### ISSUE TITLE
Build fails with Cordova iOS 8.0.0

### ISSUE THREAD

**Issue by ppetree** [apache/cordova-plugin-file-transfer#384]
# Bug Report
Build fails with Cordova iOS 8.0.0
Build is successful with Cordova iOS 7.1.1

### What is expected to happen?
Build would be successful

### What does actually happen?
Build fails.  Comment out the plugin and the build is successful.

## Information

plugin version 2.0.0
Builds with Cordova iOS 7.1.1

### Version information

Cli 8.0.0
plugin 2.0.0

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by erisu** [comment]
I ran a quick build test myself and it seems these are the errors:

```
CDVFileTransfer.m:331:65: error: no visible @interface for 'CDVPlugin' declares the
      selector 'filesystemForURL:'
  331 |         fs = [[self.commandDelegate getCommandInstance:@"File"] filesystemForURL:sourceURL];
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~

CDVFileTransfer.m:433:72: error: no visible @interface for 'CDVPlugin' declares the
      selector 'fileSystemURLforLocalPath:'
  433 |         targetURL = [[self.commandDelegate getCommandInstance:@"File"] fileSystemURLforLocalPath:target].url;
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nathan-castlehow** [comment]
Hi Team,

Looks like this one got fixed.
@erisu  any plans to cut a release with this one in it?
Its obviously a small one but a bit of a rough edge when trying to upgrade cordova-ios.

Thanks so much for everyones work on this project! <3

**Comment by GitToTheHub** [comment]
I try to bring a release forward :)

**Comment by GitToTheHub** [comment]
The release is out: https://cordova.apache.org/announcements/2026/08/10/cordova-plugin-file-transfer-2.0.1.html
